global:
  scrape_interval:   60s
  evaluation_interval: 60s
 
scrape_configs:
  - job_name: 'prometheus-server'
    static_configs:
    - targets: ['0.0.0.0:9090']
#     labels:
#      instance: prometheus
 
  - job_name: 'node-expoter'
    static_configs:
    - targets: ['120.48.106.87:9100']
#     labels:
#      instance: localhost
